service:
  enabled: false
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: service
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: metrics

deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

pod:
  restartPolicy: Always
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

container:
  imagePullPolicy: IfNotPresent
  ports:
    - name: service
      containerPort: 8080
  livenessProbe:
    httpGet:
      path: /livez
      port: service
  readinessProbe:
    httpGet:
      path: /readyz
      port: service
  securityContext:
    allowPrivilegeEscalation: false

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
  ingressClassName: nginx
  hosts:
    - host: service.local
      paths:
        - path: /
          pathType: Prefix
