service:
  type: ClusterIP
  port: 8081
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: service

deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

pod:
  imagePullSecrets: regcred
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

container:
  ports:
    - name: service
      containerPort: 8080
  livenessProbe:
    httpGet:
      path: /livez
      port: service
  readinessProbe:
    httpGet:
      path: /readyz
      port: service

ingress:
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: acme-prod
    nginx.ingress.kubernetes.io/service-upstream: "true"
