{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
   {{- include "service.labels" . | nindent 4 }}
   {{- with .Values.service.labels }}
   {{- toYaml . | nindent 4 }}
   {{- end }}
spec:
  selector:
   {{- include "service.selectorLabels" . | nindent 4 }}
   {{- with .Values.service.ports }}
  ports:
   {{- toYaml . | nindent 4 }}
   {{- end }}
   {{- with .Values.service.type }}
  type: {{ .Values.service.type }}
   {{- end }}
{{- end }}
