apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  type: {{ .Values.service.type }}
